# Site settings
title: "松林先森"
email: cdubin1991@163.com 
description: "A dark blog theme for Jekyll."
baseurl: ""
url: "http://liwenbin1991.github.io/MyBlog"
#title_description: "A dark blog theme for Jekyll focusing on a clear reading experience. Large text and a narrow body makes carte noire a gorgeous read. With excellent code snippet support and integrated tools such as AddThis and Disqus giving your Jekyll blog all the functionality your users expect."
title_description: "这是一个关于技术的Blog，是我个人在平时解决的问题的一个归纳总结，也是为了方便今后的查询。"
#title_image: "./_date/46.jpg"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: http://liwenbin1991.github.io/MyBlog 
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: 李文彬
github_username:  liwenbin1991
linkedin_link: http://liwenbin1991.github.io/MyBlog
google_plus_link: http://liwenbin1991.github.io/MyBlog
stackoverflow_link: http://liwenbin1991.github.io/MyBlog

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/liwenbin1991/MyBlog\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
